package com.ws.cxf.spring.tomcat.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-09T22:55:42.029+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://server.tomcat.spring.cxf.ws.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.tomcat.spring.cxf.ws.com/", className = "com.ws.cxf.spring.tomcat.server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.tomcat.spring.cxf.ws.com/", className = "com.ws.cxf.spring.tomcat.server.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
